### ISSUE TITLE
1.0.5 version doesn't compatible with WooCommerce 3.0

### ISSUE THREAD

**Issue by amraja** [iconicwp/shortcode-pagination-for-woocommerce#1]
shortcode-pagination-for-woocommerce  1.0.5  doesn't compatible with WooCommerce 3.0.
how to fix this problem?

**Comment by iconicwp** [comment]
-- Please reply above this line --


Hello Iconicwp/shortcode-Pagination-For-Woocom,

We received your email request! Someone from our team will get back to
you as soon as possible.

Thank you!

**Comment by amraja** [comment]
no answer?

**Comment by jamesckemp** [comment]
Hey @amraja 

Sorry for the delay. I'll be working on this soon! Not 100% sure when it will be ready yet.

**Comment by iconicwp** [comment]
-- Please reply above this line --


Hey Iconicwp/shortcode-Pagination-For-Woocom,

 Thanks for contacting Iconic!

 This is just a quick note to let you know I have received your email,
and will respond as soon as I can.

 My support hours are between 9AM-5PM GMT MONDAY TO FRIDAY, but it may
take up to 48 HOURS for me to get back to you.

 In the meantime, please check the documentation site [1] for answers
to our most frequently asked questions.

 Thanks,
 James

Links:
------
[1] http://docs.iconicwp.com
